name = "AngularSpectra"
uuid = "645da74b-6153-4148-bdaa-45095e55bacb"
authors = ["Andrew Kille"]
version = "0.1.0"

[deps]
Integrals = "de52edbc-65ea-441a-8357-d3a637375a31"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[compat]
julia = "1.10.4"
Integrals = "4.4.1"
LinearAlgebra = "1.9"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
