name = "AngularSpectrum"
uuid = "645da74b-6153-4148-bdaa-45095e55bacb"
authors = ["Andrew Kille"]
version = "0.1.0"

[compat]
julia = "1.10.4"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
